# Generated by Django 5.1.2 on 2025-11-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('requisitos', models.TextField(blank=True)),
                ('precio_referencial', models.DecimalField(blank=True, decimal_places=2, help_text='Monto en pesos chilenos (opcional).', max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trámite',
                'verbose_name_plural': 'Trámites',
                'ordering': ['nombre'],
            },
        ),
    ]
