# Generated by Django 5.1.2 on 2025-11-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_tramite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escritura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_seguimiento', models.CharField(help_text='Código que se entrega al cliente para revisar el estado.', max_length=20, unique=True)),
                ('tipo', models.CharField(help_text='Ej: Compraventa, Poder, etc.', max_length=100)),
                ('nombre_cliente', models.CharField(blank=True, max_length=200)),
                ('rut_cliente', models.CharField(blank=True, max_length=12)),
                ('estado', models.CharField(choices=[('recibido', 'Recibido'), ('en_redaccion', 'En redacción'), ('en_firma', 'En firma'), ('listo_retiro', 'Listo para retiro'), ('entregado', 'Entregado'), ('anulado', 'Anulado')], default='recibido', max_length=20)),
                ('observaciones_publicas', models.TextField(blank=True, help_text="Texto visible para el cliente (ej: 'Pendiente de retiro').")),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Escritura',
                'verbose_name_plural': 'Escrituras',
            },
        ),
    ]
