# Generated by Django 5.1.2 on 2025-11-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0004_escritura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_seguimiento', models.CharField(editable=False, max_length=20, unique=True)),
                ('tipo', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('recibido', 'Recibido'), ('en_redaccion', 'En redacción'), ('en_firma', 'En firma'), ('listo_retiro', 'Listo para retiro'), ('entregado', 'Entregado'), ('anulado', 'Anulado')], default='recibido', max_length=20)),
                ('observaciones_publicas', models.TextField(blank=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Escritura',
        ),
    ]
