# Generated by Django 5.1.2 on 2025-11-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0005_expediente_delete_escritura'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='rut_cliente',
            field=models.CharField(blank=True, help_text='Ej: 11.111.111-1 (opcional)', max_length=12),
        ),
    ]
