# Generated by Django 5.1.2 on 2025-11-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0006_expediente_rut_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudEscritura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('tipo_escritura', models.CharField(choices=[('compraventa', 'Compraventa'), ('poder', 'Poder'), ('arrendamiento', 'Arrendamiento'), ('otros', 'Otro tipo de escritura')], max_length=50)),
                ('descripcion', models.TextField(help_text='Describe brevemente el motivo o antecedentes de la escritura.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Escritura',
                'verbose_name_plural': 'Solicitudes de Escrituras',
                'ordering': ['-creado_en'],
            },
        ),
    ]
