# Generated by Django 5.1.2 on 2026-03-16 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0008_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='solicitud',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expediente', to='paginas.solicitudescritura'),
        ),
    ]
