# Generated by Django 5.1.2 on 2026-03-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0009_expediente_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='fecha_notificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='notificado_cliente',
            field=models.BooleanField(default=False),
        ),
    ]
