# Generated by Django 5.1.2 on 2026-03-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0010_expediente_fecha_notificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndiceEscritura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparecientes', models.TextField()),
                ('materia', models.CharField(max_length=255)),
                ('fecha', models.CharField(blank=True, help_text='Ej: 31-12', max_length=20)),
                ('numero_repertorio', models.CharField(blank=True, max_length=50)),
                ('foja', models.CharField(blank=True, max_length=50)),
                ('anio', models.PositiveIntegerField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Índice de Escritura Pública',
                'verbose_name_plural': 'Índices de Escrituras Públicas',
                'ordering': ['-anio', '-numero_repertorio'],
            },
        ),
    ]
