# Generated by Django 5.1.2 on 2026-03-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0011_indiceescritura'),
    ]

    operations = [
        migrations.AddField(
            model_name='indiceescritura',
            name='acto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='indiceescritura',
            name='objeto',
            field=models.TextField(blank=True),
        ),
    ]
