# Generated by Django 5.1.2 on 2026-03-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0012_indiceescritura_acto_indiceescritura_objeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('valor', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
