# Generated by Django 5.1.2 on 2026-03-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0013_valorservicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valorservicio',
            options={'ordering': ['categoria', 'orden', 'nombre']},
        ),
        migrations.AddField(
            model_name='valorservicio',
            name='descripcion_corta',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='valorservicio',
            name='descripcion_larga',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='valorservicio',
            name='icono',
            field=models.CharField(blank=True, default='📄', max_length=20),
        ),
    ]
