# Generated by Django 5.1.2 on 2026-03-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0017_recuperacionclave'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudescritura',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Solicitud de Trámite', 'verbose_name_plural': 'Solicitudes de Trámites'},
        ),
        migrations.AddField(
            model_name='solicitudescritura',
            name='area',
            field=models.CharField(choices=[('notaria', 'Notaría'), ('conservador', 'Conservador')], default='notaria', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudescritura',
            name='descripcion',
            field=models.TextField(help_text='Describe brevemente el motivo o antecedentes del trámite.'),
        ),
        migrations.AlterField(
            model_name='solicitudescritura',
            name='tipo_escritura',
            field=models.CharField(choices=[('compraventa', 'Compraventa'), ('poder', 'Poder'), ('arrendamiento', 'Arrendamiento'), ('alzamiento', 'Alzamiento'), ('mutuo', 'Mutuo'), ('hipoteca', 'Hipoteca'), ('prenda', 'Prenda'), ('resciliacion', 'Resciliación'), ('otros_notaria', 'Otro trámite notarial'), ('inscripcion_dominio', 'Inscripción de dominio'), ('hipotecas_gravamenes', 'Hipotecas y gravámenes'), ('interdicciones_prohibiciones', 'Interdicciones y prohibiciones'), ('certificados', 'Certificados'), ('archivo_documentos', 'Archivo de documentos'), ('copias_inscripciones', 'Copias de inscripciones'), ('otros_conservador', 'Otro trámite de conservador')], max_length=50),
        ),
    ]
