# Generated by Django 5.1.2 on 2026-03-26 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0018_alter_solicitudescritura_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorservicio',
            name='tramite_codigo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
