# Generated by Django 5.1.2 on 2026-03-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0019_valorservicio_tramite_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorservicio',
            name='mostrar_valor',
            field=models.BooleanField(default=True),
        ),
    ]
